package real.Objects.GUI;

import java.awt.Font;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import real.Objects.Services.MainWindow;

public class HelpWindow extends javax.swing.JFrame {

    public HelpWindow() {
        initComponents();
        initTree();
        textArea.setFont(MainWindow.getStandardFont().deriveFont(Font.PLAIN, 13));
        tree.setFont(MainWindow.getStandardFont().deriveFont(Font.PLAIN, 13));
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        tree = new javax.swing.JTree();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        textArea.setEditable(false);
        textArea.setColumns(20);
        textArea.setFont(new java.awt.Font("Cambria", 0, 13)); // NOI18N
        textArea.setLineWrap(true);
        textArea.setRows(5);
        textArea.setText("\nWelcome to the ReAl help file.\n\nPlease select an item from the tree to the left to get started.");
        textArea.setWrapStyleWord(true);
        jScrollPane2.setViewportView(textArea);

        jScrollPane1.setViewportView(tree);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initTree() {
        DefaultMutableTreeNode root = new DefaultMutableTreeNode("Help");

        DefaultMutableTreeNode gettingStarted = new DefaultMutableTreeNode("Getting started");
        gettingStarted.add(new DefaultMutableTreeNode("Datasets"));
        gettingStarted.add(new DefaultMutableTreeNode("Worksheets"));
        gettingStarted.add(new DefaultMutableTreeNode("Saving and loading"));
        gettingStarted.add(new DefaultMutableTreeNode("Keybinds"));
        gettingStarted.add(new DefaultMutableTreeNode("Auto-complete"));
        root.add(gettingStarted);

        DefaultMutableTreeNode treeView = new DefaultMutableTreeNode("Tree view");
        treeView.add(new DefaultMutableTreeNode("Running treeview"));
        treeView.add(new DefaultMutableTreeNode("Tree view features"));
        root.add(treeView);

        DefaultMutableTreeNode operations = new DefaultMutableTreeNode("Operations");
        operations.add(new DefaultMutableTreeNode("Projection"));
        operations.add(new DefaultMutableTreeNode("Selection"));
        operations.add(new DefaultMutableTreeNode("Rename"));
        operations.add(new DefaultMutableTreeNode("Group"));
        operations.add(new DefaultMutableTreeNode("Sort"));
        operations.add(new DefaultMutableTreeNode("Remove duplicates"));
        operations.add(new DefaultMutableTreeNode("Arrow"));
        operations.add(new DefaultMutableTreeNode("Union"));
        operations.add(new DefaultMutableTreeNode("Intersection"));
        operations.add(new DefaultMutableTreeNode("Difference"));
        operations.add(new DefaultMutableTreeNode("Product"));
        operations.add(new DefaultMutableTreeNode("Natural join"));
        operations.add(new DefaultMutableTreeNode("Theta join"));
        operations.add(new DefaultMutableTreeNode("Left outer join"));
        operations.add(new DefaultMutableTreeNode("Right outer join"));
        operations.add(new DefaultMutableTreeNode("Full outer join"));
        root.add(operations);

        tree.setModel(new DefaultTreeModel(root));
        tree.addTreeSelectionListener(new TreeSelectionListener()
        {
            @Override
            public void valueChanged(TreeSelectionEvent e)
            {
                DefaultMutableTreeNode node = (DefaultMutableTreeNode)
                        tree.getLastSelectedPathComponent();
                loadText(node.toString());
            }
        });
    }

    private void loadText(String item) {
        try
        {
            InputStreamReader reader = new InputStreamReader(
                    new FileInputStream("assets/helpfiles/english/" + item + ".txt"), "UTF-8");
            textArea.setText("");
            textArea.read(reader, null);
        }
        catch (IOException ex)
        {
            textArea.setText("");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea textArea;
    private javax.swing.JTree tree;
    // End of variables declaration//GEN-END:variables
}
