package real.Objects.GUI;

import java.awt.AWTException;
import java.io.File;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import real.BaseClasses.OperationBase;
import real.Objects.Utility;

public class TreeWindow extends javax.swing.JDialog
{
    public TreeWindow(java.awt.Frame parent, boolean modal, OperationBase tree)
    {
        super(parent, modal);
        initComponents();
        treeView.initialize(this);
        treeView.loadTree(tree);   
    }

    public JTable getTableView()
    {
        return this.tableView;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        saveFileChooser = new javax.swing.JFileChooser();
        treeView = new real.Objects.GUI.TreeView();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableView = new javax.swing.JTable();

        saveFileChooser.setAcceptAllFileFilterUsed(false);
        saveFileChooser.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        saveFileChooser.setDialogTitle("Save");
        saveFileChooser.setFileFilter(new ExtensionFileFilter("png", new String[]{"png"}));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        treeView.setPreferredSize(new java.awt.Dimension(400, 255));
        getContentPane().add(treeView, java.awt.BorderLayout.CENTER);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButton1.setText("Save To Image");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_END);

        tableView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableView);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        int returnVal = saveFileChooser.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION)
        {
            File file = new File(Utility.addExtension(saveFileChooser.getSelectedFile().getAbsolutePath(), ".png"));
            
            try
            {
                this.treeView.drawImage(file);
            }
            catch (IOException | AWTException ex)
            {
                JOptionPane.showMessageDialog(rootPane, "Problem saving file at " + file.getAbsolutePath());
            }
        }
        else
        {
            System.out.println("File save cancelled by user.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JFileChooser saveFileChooser;
    private javax.swing.JTable tableView;
    private real.Objects.GUI.TreeView treeView;
    // End of variables declaration//GEN-END:variables
}
